name: hugo2ftp

on:
  push:
    branches:
      - mastersftp

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
        
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true 

      - name: Build
        run: hugo --minify
      
      - name: SFTP Deploy
        run:  sshpass -p "${{ secrets.SFTP_PASSWORD }}" rsync lxol_hugo@lxol.ftp.infomaniak.com:/web/hugo /public
